name: Update Fishing Schedule

on:
  schedule:
    - cron: '0 * * * *' # 1時間ごと
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v3からv4へ

      - name: Set up Python
        uses: actions/setup-python@v5 # v4からv5へ
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager
          
      - name: Run script
        run: python github_test.py
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # 明示的にNode.js 24を使用

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fishing_schedule.json
          git commit -m "Update schedule" || exit 0
          git push
